steps:
  # Step 1: Build the mern-server Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mern-server', './mern/server']
    id: 'build-mern-server'

  # Step 2: Build the mern-client Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mern-client', './mern/client']
    id: 'build-mern-client'

  # Step 3: Push the mern-server Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mern-server']
    waitFor: ['build-mern-server']

  # Step 4: Push the mern-client Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mern-client']
    waitFor: ['build-mern-client']

  # Step 5: Deploy with Docker Compose
  - name: 'gcr.io/cloud-builders/docker-compose'
    args: ['-f', 'docker-compose.yaml', 'up', '--build', '-d']
    id: 'deploy-mern-stack'

images:
  - 'gcr.io/$PROJECT_ID/mern-server'
  - 'gcr.io/$PROJECT_ID/mern-client'
