options:
  logging: CLOUD_LOGGING_ONLY
projectId: gem-creation
steps:
  - name: 'gcr.io/cloudbuild/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/gem-creation/buildpacks-docker-repo/mern-server:latest', '.']
  - name: 'gcr.io/cloudbuild/docker'
    args: ['push', 'us-central1-docker.pkg.dev/gem-creation/buildpacks-docker-repo/mern-server:latest']
images:
  - us-central1-docker.pkg.dev/gem-creation/buildpacks-docker-repo/mern-server:latest
