steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mern-server', './mern/server']
    id: 'build-mern-server'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mern-client', './mern/client']
    id: 'build-mern-client'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mern-server']
    waitFor: ['build-mern-server']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mern-client']
    waitFor: ['build-mern-client']

  - name: 'gcr.io/cloud-builders/docker-compose'
    args: ['-f', 'docker-compose.yaml', 'up', '--build', '-d']
    id: 'deploy-mern-stack'

images:
  - 'gcr.io/$PROJECT_ID/mern-server'
  - 'gcr.io/$PROJECT_ID/mern-client'

options:
  logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging only
