version: '3.8'

services:
  server:
    image: surfiniaburger/mern-server
    container_name: mern_server
    restart: unless-stopped
    env_file:
      - ./mern/server/config.env
    ports:
      - "5050:5050"
    depends_on:
      - mongo
    networks:
      - mern-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/record/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:6.0
    container_name: mern_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_mongo_username
      MONGO_INITDB_ROOT_PASSWORD: your_mongo_password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
