version: '3.8'

services:
  client:
    image: surfiniaburger/mern-client
    container_name: mern_client
    restart: unless-stopped
    ports:
      - "3001:80"
    depends_on:
      - server  # Optional: Remove if frontend doesn't directly depend on backend at runtime
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
