// server/utils/verification.js

import * as snarkjs from 'snarkjs';

/**
 * Verify a zk-SNARK proof using the provided verification key.
 *
 * @param {Object} vKey - Verification key JSON object.
 * @param {Object} proof - Proof object generated by snarkjs.
 * @param {Array} publicSignals - Public signals from the proof.
 * @returns {Boolean} - True if proof is valid, else false.
 */
export const verifyProof = async (vKey, proof, publicSignals) => {
    try {
        const isValid = await snarkjs.groth16.verify(vKey, publicSignals, proof);
        return isValid;
    } catch (error) {
        console.error("Error verifying proof:", error);
        return false;
    }
};
